### PR TITLE
Updates for Sketch 47

### PR DESCRIPTION
**Pull request by norm0**
Found this fix from the Content-generator-sketch-plugin to update to Sketch 47.

### CODE REVIEW

**Comment by yefim** [comment]
@norm0 thanks for the PR. Do you know if this will break in Sketch 44?

**Comment by norm0** [comment]
That I did not test for.

**Comment by yefim** [comment]
I'll test it then get back to you :) Hopefully there is a solution that will work for ALL Sketch versions :D

**Comment by yefim** [comment]
@norm0 I just did a bit of research on the bug and looks like this is the better way to solve it for all Sketch versions: https://github.com/maximedegreve/TinyFaces-Sketch-Plugin/commit/c9db87789d2ceba8b563ca54c96f38b487ce2da6

I'm going to close your PR and commit the fix to `master`. Thanks for bringing it to my attention!

**Comment by yefim** [comment]
Fix is here: https://github.com/reneepadgham/diverseui-sketch-plugin/commit/86b27c7d39044b659d722ecc92f98c67d175f26f

**Pull request closed without merging**
